project_name: mmore
docs_path: ../mmore/docs/source
code_path: ../mmore/src/mmore
include_extensions:
  - .md
  - .rst
  - .py
exclude_patterns:
  - "__pycache__"
  - ".ipynb_checkpoints"
  - ".DS_Store"